### ISSUE TITLE
If a player's inventory is full and other person give them items (Using Give) , it doesnt give but a person lose those given items

### ISSUE THREAD

**Issue by imbader** [qbcore-framework/qb-inventory#88]
Two players 

player 1 :
has full inventory (limit weight)
player 2:
has empty inventory with few items. 
if tend to give the player 1 some (few items) it declines that and show an error Notification (Can't Give Item) YET
the Player2. (lose those few items from their inventory)

**Comment by ihyajb** [comment]
qb-inventory currently does not have a give item feature. Please keep issues about the Official QBCore build.

**Comment by TassieRPCx** [comment]
QB-core has a check for this that is disallowing it. if you add a if then statement to otherplayer.additem like this
if otherplayer.functions.additem then 
 player.functions.removeitem 
 -- removes item when we confirmed that additem returns as true 
else 
   -- error for not being able to carry items 
end

that is basically the fix in a very basic way

**Comment by evanillaa** [comment]
There should be an official scenario, to add the item giving feature
There are some people who face a big and varied problem
The project management must adopt this feature
Officially within the project
In order to be used correctly and without problems, and everyone cooperates in discovering the gaps and problems
Everyone loves the purpose of giving item

**Comment by ihyajb** [comment]
Currently at this time we have no plans to add a "Give Item" button until all other bugs are fixed in the project. Our current goal / game plan for QBCore is to fix everything then start adding suggestions if we feel they would make a good addition to the project. Thank you.
